UOS25/BE

src/main/java/uos/uos25/product/entity/Product.java, src/main/java/uos/uos25/product/exception/ProductNotFoundException.java, src/main/java/uos/uos25/product/repository/ProductRepository.java, src/main/java/uos/uos25/product/service/ProductService.java, src/main/java/uos/uos25/shop/entity/Shop.java, src/main/java/uos/uos25/shop/exception/ShopNotFoundException.java, src/main/java/uos/uos25/shop/repository/ShopRepository.java, src/main/java/uos/uos25/shop/service/ShopService.java
- 지점(Shop) Id로 조회하는 findById 기능 구현
- 상품(Product) Id로 조회하는 findById 기능 구현
- 각각 Id 데이터 타입 String -> Long으로 변경
=> feat: 지점, 상품 찾기 기능 구현

src/main/java/uos/uos25/Employee/entity/Employee.java, src/main/java/uos/uos25/customer/entity/Customer.java, src/main/java/uos/uos25/product/controller/ProductController.java, src/main/java/uos/uos25/product/dto/ProductDTO.java, src/main/java/uos/uos25/product/dto/request/ProductInfoRequestDTO.java, src/main/java/uos/uos25/product/dto/response/ProductInfoResponseDTO.java, src/main/java/uos/uos25/product/entity/Product.java, src/main/java/uos/uos25/product/repository/ProductRepository.java, src/main/java/uos/uos25/product/service/ProductService.java, src/main/java/uos/uos25/shop/entity/Shop.java
=> feat: 상품 조회 기능 구현

src/main/java/uos/uos25/Employee/DTO/EmployeeDTO.java, src/main/java/uos/uos25/Employee/entity/Employee.java, src/main/java/uos/uos25/Employee/entity/EmployeeWorkingHistory.java, src/main/java/uos/uos25/customer/entity/Customer.java, src/main/java/uos/uos25/disposal/entity/Disposal.java, src/main/java/uos/uos25/entity/Event.java, src/main/java/uos/uos25/entity/ReceiptDetail.java, src/main/java/uos/uos25/headQuarter/entity/HeadQuarter.java, src/main/java/uos/uos25/inventory/entity/Inventory.java, src/main/java/uos/uos25/orders/entity/Orders.java, src/main/java/uos/uos25/product/entity/Product.java, src/main/java/uos/uos25/receipt/entity/Receipt.java, src/main/java/uos/uos25/returns/entity/Returns.java, src/main/java/uos/uos25/sale/entity/Sales.java, src/main/java/uos/uos25/shop/entity/Shop.java, src/main/resources/application.yml, src/test/java/uos/uos25/Employee/service/EmployeeServiceTest.java
- 작성해주신 속성 정의서를 참고하여 도메인을 전체적으로 수정했습니다. 
- 거의 모든 컬럼에 `@Column(nullable = false)`를 깔았습니다.
- 소수의 널을 허용하는 컬럼에는 `@Column(nullable = true)`를 명시하였습니다.
- 모든 아이디 컬럼을 Long으로, 그 외 숫자 컬럼을 Integer로 통일하였습니다.
- 예외로, EmployeeWorkingHistory의 WorkingHour의 경우 Long으로 유지하였습니다. Duration 클래스가 리턴 값으로 Long을 지원해서, Long-> Integer로 캐스팅해서 쓰는 것보다 그냥 컬럼을 Long으로 잡는게 안전하다고 생각했습니다.
- 도메인만 건드려서 아마 다른 오류는 발생 안하지 않을까...요? 일단 서버는 잘 켜져요..
=> fix: domain 전체 수정

src/main/java/uos/uos25/Employee/entity/Employee.java, src/main/java/uos/uos25/Employee/entity/EmployeeWorkingHistory.java, src/main/java/uos/uos25/common/DataInitializer.java, src/main/java/uos/uos25/customer/DTO/request/CustomerRequestDTO.java, src/main/java/uos/uos25/customer/DTO/response/CustomerResponseDTO.java, src/main/java/uos/uos25/customer/controller/CustomerController.java, src/main/java/uos/uos25/customer/entity/Customer.java, src/main/java/uos/uos25/customer/exception/CustomerExceptionHandler.java, src/main/java/uos/uos25/customer/exception/CustomerNotFoundException.java, src/main/java/uos/uos25/customer/repository/CustomerRepository.java, src/main/java/uos/uos25/customer/service/CustomerService.java, src/main/java/uos/uos25/headQuarter/entity/HeadQuarter.java, src/main/java/uos/uos25/headQuarter/repository/HeadQuarterRepository.java, src/main/java/uos/uos25/orders/entity/Orders.java, src/main/java/uos/uos25/returns/entity/Returns.java, src/main/java/uos/uos25/shop/entity/Shop.java
두 번째 주 기능 구현입니다! :) 알려주신 점 최대한 활용해서 깔끔한 코드를 짜보려고 노력했습니다.  
아 그리고, `@ColumnDefault` 어노테이션 이거 쓸모 없더라고요.. 전 이거 쓰면 디폴트값이 딱딱 들어가는줄 알았는데, `ddl-auto:  create-drop`일 때에만 작동하더라고요... 그래서 일단 지웠습니다. 디폴트 값 처리할 때에는 엔티티 쪽이나 DTO 쪽에서 해줘야 할 것 같습니다!
- customer join
- customer find
- findById
- findAll
- customer update
- customer delete
이상 기본 CRUD 구현했습니다.
- customer earnMileage
- 이부분 구매 과정이랑 어떻게 연계되는지 몰라서, 일단 `@RequestBody`쪽에 적립받을 마일리지를 인티저로 받는 식으로 구현했습니다. 추후에 구매 과정 코딩 완료되면 그 방식에 맞게 수정하겠습니다!
- DataInitializer 작성
- 이하 내용은 제가 더미 데이터 넣으면서 체크용으로 작성한 md 파일이라, 형식이 자유롭습니다^ㅡ^.. 혹시 참고가 되실까 싶어 첨부하였습니다.
더미 하나씩 넣었습니다^ㅡ^
1. HeadQuarter
- HQ repository 만듦
- baseEntity 상속 X
- HQ 더미 만듦
2. Shop
- shop repository에 builder 만듦
- shop 더미 만듦
3. Orders
- Orders 더미 만듦
- @ColumnDefault 제거. 의미 없다고 함.
4. Returns
- Returns 더미 만듦
- …
=> feat: Customer 주 기능 구현

src/main/java/uos/uos25/product/controller/ProductController.java, src/main/java/uos/uos25/product/dto/response/ProductInfoResponseDTO.java, src/main/java/uos/uos25/product/entity/Product.java, src/main/java/uos/uos25/product/service/ProductService.java
- 리스폰스 dto 필드 변경(노션에 작업 완료)
- lazy 로딩으로 변경(응답값 dto로 변경해서 의미 없음)
- 상품 조회 id랑 barcode로 검색하는 endpoint 나눔
=> fix: 상품 조회 변경

src/main/java/uos/uos25/common/DataInitializer.java, src/main/java/uos/uos25/disposal/service/DisposalService.java, src/main/java/uos/uos25/event/controller/EventController.java, src/main/java/uos/uos25/event/dto/request/EventCreateRequestDTO.java, src/main/java/uos/uos25/event/dto/response/EventCreateResponseDTO.java, src/main/java/uos/uos25/event/dto/response/EventGetResponseDTO.java, src/main/java/uos/uos25/event/entity/Event.java, src/main/java/uos/uos25/event/exception/EventNotFound.java, src/main/java/uos/uos25/event/repository/EventRepository.java, src/main/java/uos/uos25/event/service/EventService.java, src/main/java/uos/uos25/inventory/service/InventoryService.java, src/main/java/uos/uos25/orders/service/OrdersService.java, src/main/java/uos/uos25/product/controller/ProductController.java, src/main/java/uos/uos25/product/dto/response/ProductInfoResponseDTO.java, src/main/java/uos/uos25/product/entity/Product.java, src/main/java/uos/uos25/product/service/ProductService.java, src/main/java/uos/uos25/purchase/sevice/PurchaseService.java, src/main/java/uos/uos25/receipt/service/ReceiptDetailService.java, src/main/java/uos/uos25/receipt/service/ReceiptService.java, src/main/java/uos/uos25/returns/service/ReturnsService.java
- 이벤트 생성 기능 구현
- 이벤트 ID로 조회 기능 구현
- 이벤트 전체 조회 기능 구현
=> feat: 이벤트 기능 구현

src/main/java/uos/uos25/common/DataInitializer.java, src/main/java/uos/uos25/customer/entity/Customer.java, src/main/java/uos/uos25/receipt/controller/ReceiptController.java, src/main/java/uos/uos25/receipt/entity/Receipt.java, src/main/java/uos/uos25/receipt/repository/ReceiptRepository.java, src/main/java/uos/uos25/receipt/service/ReceiptService.java
- 고객 전화번호(PK)로 영수증 조회 기능 구현
- 영수증 - 고객 fk 버그 수정
- 더미 데이터 추가
=> feat: 영수증 고객 전화번호 조회 기능 구현

src/main/java/uos/uos25/customer/controller/CustomerController.java, src/main/java/uos/uos25/customer/dto/request/CustomerCreateRequestDTO.java, src/main/java/uos/uos25/customer/dto/request/CustomerUpdateRequestDTO.java, src/main/java/uos/uos25/customer/dto/response/CustomerCreateResponseDTO.java, src/main/java/uos/uos25/customer/dto/response/CustomerGetResponseDTO.java, src/main/java/uos/uos25/customer/dto/response/CustomerMileageGetResponseDTO.java, src/main/java/uos/uos25/customer/dto/response/CustomerUpdateResponseDTO.java, src/main/java/uos/uos25/customer/entity/Customer.java, src/main/java/uos/uos25/customer/service/CustomerService.java, src/main/java/uos/uos25/purchase/controller/PurchaseController.java, src/main/java/uos/uos25/purchase/dto/request/PurchaseRequestDTO.java, src/main/java/uos/uos25/purchase/sevice/PurchaseService.java, src/main/java/uos/uos25/receipt/entity/ReceiptDetail.java, src/main/java/uos/uos25/receipt/service/ReceiptService.java, src/main/java/uos/uos25/util/MileageUtil.java
- 구매 시 마일리지 적립 기능 구현
- 고객 마일리지 조회 기능 구현
- 고객 기능 리팩토링
=> feat: 마일리지 적립 기능 구현

src/main/java/uos/uos25/customer/controller/CustomerController.java, src/main/java/uos/uos25/disposal/entity/Disposal.java, src/main/java/uos/uos25/event/entity/Event.java, src/main/java/uos/uos25/inventory/entity/Inventory.java, src/main/java/uos/uos25/orders/entity/Orders.java, src/main/java/uos/uos25/receipt/entity/ReceiptDetail.java, src/main/java/uos/uos25/returns/entity/Returns.java
=> fix: 상품 FK 명 변경

build.gradle, src/main/java/uos/uos25/common/config/SwaggerConfig.java, src/main/java/uos/uos25/customer/controller/CustomerController.java, src/main/java/uos/uos25/disposal/controller/DisposalController.java, src/main/java/uos/uos25/employee/controller/EmployeeController.java, src/main/java/uos/uos25/employee/controller/EmployeeWorkingHistoryController.java, src/main/java/uos/uos25/event/controller/EventController.java, src/main/java/uos/uos25/inventory/controller/InventoryController.java, src/main/java/uos/uos25/orders/controller/OrdersController.java, src/main/java/uos/uos25/product/controller/ProductController.java, src/main/java/uos/uos25/purchase/controller/PurchaseController.java, src/main/java/uos/uos25/receipt/controller/ReceiptController.java, src/main/java/uos/uos25/receipt/controller/ReceiptDetailController.java, src/main/java/uos/uos25/returns/controller/ReturnsController.java, src/main/java/uos/uos25/shop/controller/ShopController.java, src/main/resources/application.yml
- 스웨거 추가
- 컨트롤러 스웨거 태그 추가
- dotenv로 민감정보 관리
=> feat: 스웨거 추가

src/main/java/uos/uos25/employee/controller/EmployeeController.java, src/main/java/uos/uos25/employee/controller/EmployeeWorkingHistoryController.java, src/main/java/uos/uos25/employee/dto/EmployeeWorkingHistoryDTO.java, src/main/java/uos/uos25/employee/dto/request/EmployeeCreateReqeustDTO.java, src/main/java/uos/uos25/employee/dto/request/EmployeeCreateResponseDTO.java, src/main/java/uos/uos25/employee/dto/request/EmployeeUpdateReqeustDTO.java, src/main/java/uos/uos25/employee/dto/response/EmployeeCreateResponseDTO.java, src/main/java/uos/uos25/employee/dto/response/EmployeeGetResponseDTO.java, src/main/java/uos/uos25/employee/entity/Employee.java, src/main/java/uos/uos25/employee/service/EmployeeService.java, src/main/java/uos/uos25/employee/service/EmployeeWorkingHistoryService.java
- 기존 코드 리팩토링
- 직원 업데이트 null 체크
- request DTO 예시 추가
- 직원 생성 시 id 추가
- 직원 퇴사 설명 추가
=> feat: 직원 기능 추가

src/main/java/uos/uos25/customer/controller/CustomerController.java, src/main/java/uos/uos25/customer/dto/request/CustomerCreateRequestDTO.java, src/main/java/uos/uos25/customer/dto/request/CustomerMileageUpdateRequestDTO.java, src/main/java/uos/uos25/customer/dto/request/CustomerUpdateRequestDTO.java, src/main/java/uos/uos25/customer/entity/Customer.java, src/main/java/uos/uos25/customer/service/CustomerService.java
=> refator: request dto 예시 추가

src/main/java/uos/uos25/customer/controller/CustomerController.java, src/main/java/uos/uos25/customer/dto/request/CustomerCreateRequestDTO.java, src/main/java/uos/uos25/customer/dto/request/CustomerMileageUpdateRequestDTO.java, src/main/java/uos/uos25/customer/dto/request/CustomerUpdateRequestDTO.java, src/main/java/uos/uos25/customer/entity/Customer.java, src/main/java/uos/uos25/customer/service/CustomerService.java
=> chore: request dto 예시 추가

src/main/java/uos/uos25/common/DataInitializer.java, src/main/java/uos/uos25/employee/dto/request/EmployeeCreateReqeustDTO.java, src/main/java/uos/uos25/employee/dto/request/EmployeeUpdateReqeustDTO.java, src/main/java/uos/uos25/employee/dto/response/EmployeeCreateResponseDTO.java, src/main/java/uos/uos25/employee/dto/response/EmployeeGetResponseDTO.java, src/main/java/uos/uos25/employee/entity/Employee.java, src/main/java/uos/uos25/employee/service/EmployeeService.java
=> feat: Employee에 bank 추가

src/main/java/uos/uos25/common/DataInitializer.java, src/main/java/uos/uos25/inventory/entity/Inventory.java
=> fix: 상품 구매 시 display 개수 차감

src/main/java/uos/uos25/receipt/controller/ReceiptController.java, src/main/java/uos/uos25/receipt/repository/ReceiptRepository.java, src/main/java/uos/uos25/receipt/service/ReceiptService.java
=> fix: 영수증 복수 조회 에러 수정

src/main/java/uos/uos25/receipt/controller/ReceiptController.java, src/main/java/uos/uos25/receipt/dto/response/ReceiptGetResponseDTO.java, src/main/java/uos/uos25/receipt/service/ReceiptService.java
=> fix: 영수증 조회 시 상태 추가

src/main/java/uos/uos25/employee/controller/EmployeeWorkingHistoryController.java, src/main/java/uos/uos25/employee/dto/response/EmployeeWorkingHistoryGetResponseDTO.java, src/main/java/uos/uos25/employee/repository/EmployeeWorkingHistoryRepository.java, src/main/java/uos/uos25/employee/service/EmployeeWorkingHistoryService.java
=> feat: 지점 ID로 직원 출근 기록 조회 기능 구현

src/main/java/uos/uos25/employee/exception/DuplicatedHistoryException.java, src/main/java/uos/uos25/employee/exception/EmployeeExceptionHandler.java, src/main/java/uos/uos25/employee/service/EmployeeWorkingHistoryService.java
- DuplicatedHistoryException을 추가했습니다.
- ExceptionHandler에 해당 익셉션을 추가했습니다.
- EmployeeWorkingHistoryService의 startWorking에서 DuplicatedHistoryException을 던지도록 수정했습니다.
=> fix: 중복 출근 예외처리 변경

src/main/java/uos/uos25/common/DataInitializer.java, src/main/java/uos/uos25/shop/controller/DisbursementController.java, src/main/java/uos/uos25/shop/dto/response/DisbursementGetResponseDTO.java, src/main/java/uos/uos25/shop/entity/Disbursement.java, src/main/java/uos/uos25/shop/entity/Shop.java, src/main/java/uos/uos25/shop/repository/DisbursementRepository.java, src/main/java/uos/uos25/shop/service/DisbursementService.java
- 자금출납 전체 조회 기능 구현
- 자금출납 지점별 조회 기능 구현
=> feat: 자금출납 조회 기능 추가

src/main/java/uos/uos25/shop/controller/DisbursementController.java, src/main/java/uos/uos25/shop/repository/DisbursementRepository.java, src/main/java/uos/uos25/shop/service/DisbursementService.java
=> feat: 자금출납 직원별 조회 기능 구현

src/main/java/uos/uos25/employee/controller/EmployeeController.java, src/main/java/uos/uos25/employee/dto/request/SalaryCalculationRequestDTO.java, src/main/java/uos/uos25/employee/entity/Employee.java, src/main/java/uos/uos25/employee/repository/EmployeeWorkingHistoryRepository.java, src/main/java/uos/uos25/employee/service/EmployeeService.java, src/main/java/uos/uos25/employee/service/EmployeeWorkingHistoryService.java, src/main/java/uos/uos25/shop/exception/DisbursementAlreadyExistsException.java, src/main/java/uos/uos25/shop/repository/DisbursementRepository.java, src/main/java/uos/uos25/shop/service/DisbursementService.java
- 직원 급여 정산 기능 구현
- 정산되지 않은 달만 사용 가능
- 정산된 날은 예외 처리
=> feat: 직원 급여 정산 기능 구현

src/main/java/uos/uos25/inventory/controller/InventoryController.java, src/main/java/uos/uos25/inventory/dto/response/InventoryGetResponseDTO.java
=> fix: 재고 조회 시 보관날짜, 폐기날짜 동봉

src/main/java/uos/uos25/common/BaseEntity.java, src/main/java/uos/uos25/orders/controller/OrdersController.java, src/main/java/uos/uos25/orders/dto/response/OrdersCreateResponseDTO.java, src/main/java/uos/uos25/orders/dto/response/OrdersGetResponseDTO.java
- 주문 조회 시 생성 날짜 포함
- 주문 생성 시 생성 날짜 포함
=> fix: 주문 응답값에 날짜 포함

src/main/java/uos/uos25/employee/controller/EmployeeController.java, src/main/java/uos/uos25/employee/repository/EmployeeRepository.java, src/main/java/uos/uos25/employee/service/EmployeeService.java
- 직원 이름으로 직원을 검색하는 기능을 추가하였습니다.
- 지점 아이디로 직원을 검색하는 기능을 추가하였습니다.
(24-06-08 00:55 추가)
- 직원 이름 + 지점 아이디를 모두 만족했을 때의 직원 검색 기능을 추가하였습니다.
=> feat: 직원 검색 방식 추가

src/main/java/uos/uos25/product/service/ProductService.java
=> fix: 상품에서 생활서비스 제외

src/main/java/uos/uos25/employee/service/EmployeeService.java
=> feat: shopId로 직원 검색 시 퇴사한 직원 필터

src/main/java/uos/uos25/employee/dto/EmployeeInfo.java, src/main/java/uos/uos25/employee/entity/Employee.java, src/main/java/uos/uos25/receipt/dto/response/ReceiptGetResponseDTO.java, src/main/java/uos/uos25/shop/dto/ShopInfo.java
=> feat: 영수증 조회 시 정보 추가

src/main/java/uos/uos25/common/error/ErrorCode.java, src/main/java/uos/uos25/returns/controller/ReturnsController.java, src/main/java/uos/uos25/returns/dto/response/ReturnsGetResponseDTO.java, src/main/java/uos/uos25/returns/exception/ReturnsNotFoundException.java, src/main/java/uos/uos25/returns/service/ReturnsService.java
- 반품 조회 시 날짜 추가
- 반품 id로 검색 기능 추가
=> fix: 반품 날짜 추가

src/main/java/uos/uos25/inventory/controller/InventoryController.java, src/main/java/uos/uos25/inventory/entity/Inventory.java, src/main/java/uos/uos25/inventory/repository/InventoryRepository.java, src/main/java/uos/uos25/inventory/service/InventoryService.java, src/main/java/uos/uos25/purchase/sevice/PurchaseService.java
- 진열 상품이 재고를 넘지 않도록 검증
- 진열 메서드 명 변경
- 상품 이름으로 재고 조회 기능 추가
=> fix: 재고 validate 수정

src/main/java/uos/uos25/inventory/service/InventoryService.java, src/main/java/uos/uos25/orders/controller/OrdersController.java, src/main/java/uos/uos25/orders/dto/request/OrdersCreateRequestDTO.java, src/main/java/uos/uos25/orders/dto/request/OrdersStatusRequestDTO.java, src/main/java/uos/uos25/orders/entity/Orders.java, src/main/java/uos/uos25/orders/service/OrdersService.java
=> fix: 주문 상태 변경 시 재고 추가

src/main/java/uos/uos25/common/DataInitializer.java, src/main/java/uos/uos25/common/error/ErrorCode.java, src/main/java/uos/uos25/orders/controller/OrdersController.java, src/main/java/uos/uos25/orders/dto/request/OrdersStatusRequestDTO.java, src/main/java/uos/uos25/orders/entity/OrdersStatus.java, src/main/java/uos/uos25/orders/exception/OrdersNotDelivering.java, src/main/java/uos/uos25/orders/exception/OrdersNotRequested.java, src/main/java/uos/uos25/orders/repository/OrdersRepository.java, src/main/java/uos/uos25/orders/service/OrdersService.java
- 주문 상태 enum으로 관리
- 배송 시작 상태 검증
- 검품 상태 검증
- 지점으로 주문 조회 기능 추가
=> feat: 주문 기능 추가

src/main/java/uos/uos25/employee/controller/EmployeeController.java, src/main/java/uos/uos25/employee/entity/EmployeeWorkingHistory.java, src/main/java/uos/uos25/employee/service/EmployeeService.java, src/main/java/uos/uos25/shop/controller/DisbursementController.java, src/main/java/uos/uos25/shop/dto/response/DisbursementGetResponseDTO.java, src/main/java/uos/uos25/shop/service/DisbursementService.java, src/main/java/uos/uos25/statistics/service/StatisticsService.java, src/main/java/uos/uos25/util/DateUtil.java
- 직원 급여 정산 /employee에서 /disbursement로 변경
- 날짜 관련 유틸 구현
=> refactor: 직원 급여 정산 위치 변경

src/main/java/uos/uos25/employee/controller/EmployeeWorkingHistoryController.java, src/main/java/uos/uos25/event/dto/request/EventCreateRequestDTO.java, src/main/java/uos/uos25/shop/dto/response/DisbursementGetResponseDTO.java
- DTO 예제 추가
- ResponseEntity<Void>로 변경
=> refactor: DTO에 예제 추가

src/main/java/uos/uos25/common/error/ErrorCode.java, src/main/java/uos/uos25/disposal/controller/DisposalController.java, src/main/java/uos/uos25/disposal/service/DisposalService.java, src/main/java/uos/uos25/inventory/entity/Inventory.java, src/main/java/uos/uos25/inventory/exception/InventoryEaCannotBeLowerThanDisplayEa.java, src/main/java/uos/uos25/purchase/sevice/PurchaseService.java
- 폐기 시 재고 차감 기능 구현
- 상품 구매 시 재고 개수 차감 메서드명 리팩토링
=> fix: 폐기 시 재고 차감 기능 구현

src/main/java/uos/uos25/disposal/controller/DisposalController.java, src/main/java/uos/uos25/disposal/dto/response/DisposalGetResponseDTO.java, src/main/java/uos/uos25/disposal/repository/DisposalRepository.java, src/main/java/uos/uos25/disposal/service/DisposalService.java
- 폐기 조회 시 날짜 포함
- shopId로 폐기 조회 기능 구현
=> feat: 폐기 날짜  추가

src/main/java/uos/uos25/customer/controller/CustomerController.java, src/main/java/uos/uos25/customer/service/CustomerService.java, src/main/java/uos/uos25/purchase/dto/request/PurchaseCreateRequestDTO.java, src/main/java/uos/uos25/purchase/sevice/PurchaseService.java, src/main/java/uos/uos25/receipt/entity/Receipt.java, src/main/java/uos/uos25/receipt/service/ReceiptService.java
- 고객 삭제 시 영수증 고객 컬럼 null로 변경
- 고객 없이 구매 가능하게 변경
- 고객 삭제 API 예제 추가
=> fix: 고객 삭제 시 영수증 고객 컬럼 null로 변경

src/main/java/uos/uos25/common/DataInitializer.java, src/main/java/uos/uos25/common/error/ErrorCode.java, src/main/java/uos/uos25/customer/controller/CustomerController.java, src/main/java/uos/uos25/event/dto/request/EventCreateRequestDTO.java, src/main/java/uos/uos25/event/dto/response/EventCreateResponseDTO.java, src/main/java/uos/uos25/event/dto/response/EventGetResponseDTO.java, src/main/java/uos/uos25/event/entity/Event.java, src/main/java/uos/uos25/event/service/EventService.java, src/main/java/uos/uos25/product/entity/Product.java, src/main/java/uos/uos25/purchase/controller/PurchaseController.java, src/main/java/uos/uos25/purchase/dto/response/PurchaseCancelResponseDTO.java, src/main/java/uos/uos25/purchase/sevice/PurchaseService.java, src/main/java/uos/uos25/receipt/entity/Receipt.java, src/main/java/uos/uos25/receipt/entity/ReceiptStatus.java, src/main/java/uos/uos25/receipt/exception/ReceiptCannotBeCanceledException.java, src/main/java/uos/uos25/receipt/service/ReceiptService.java, src/main/java/uos/uos25/returns/controller/ReturnsController.java
- 이벤트 가격 컬럼 추가
- 구매 시 이벤트 가격 차감
- 환불 시 영수증 상태 검증
- 환불 시 환불 금액 반환
=> fix: 이벤트 가격 컬럼 추가

src/main/java/uos/uos25/common/DataInitializer.java, src/main/java/uos/uos25/employee/controller/EmployeeController.java, src/main/java/uos/uos25/employee/dto/response/EmployeeHeadquarterGetResponseDTO.java, src/main/java/uos/uos25/employee/entity/Employee.java, src/main/java/uos/uos25/employee/entity/EmployeePosition.java, src/main/java/uos/uos25/employee/repository/EmployeeRepository.java, src/main/java/uos/uos25/employee/service/EmployeeService.java
- 직원 포지션 Enum으로 관리
- 본사 직원만 조회 기능 구현
=> feat: 본사 직원 조회 기능 구현

src/main/java/uos/uos25/common/DataInitializer.java, src/main/java/uos/uos25/shop/controller/DisbursementController.java, src/main/java/uos/uos25/shop/dto/request/DisbursementCreateRequestDTO.java, src/main/java/uos/uos25/shop/dto/request/SalaryCalculationRequestDTO.java, src/main/java/uos/uos25/shop/dto/response/DisbursementGetResponseDTO.java, src/main/java/uos/uos25/shop/entity/Disbursement.java, src/main/java/uos/uos25/shop/entity/DisbursementType.java, src/main/java/uos/uos25/shop/repository/DisbursementRepository.java, src/main/java/uos/uos25/shop/service/DisbursementService.java
- 자금 출납 유형 추가
- 본사로 자금 출납 기능 구현
=> feat: 본사로 자금 출납 기능 구현

src/main/java/uos/uos25/purchase/dto/request/PurchaseCreateRequestDTO.java, src/main/java/uos/uos25/receipt/entity/GenderType.java, src/main/java/uos/uos25/statistics/controller/StatisticsController.java, src/main/java/uos/uos25/statistics/dto/response/StatisticsAgeGetResponseDTO.java, src/main/java/uos/uos25/statistics/dto/response/StatisticsGenderGetResponseDTO.java, src/main/java/uos/uos25/statistics/dto/response/StatisticsSalesGetResponseDTO.java, src/main/java/uos/uos25/statistics/service/StatisticsService.java
- 나이에 따른 통계 조회 기능 구현
- 성별에 따른 통계 조회 기능 구현
=> feat: 통계 기능 제공

src/main/java/uos/uos25/employee/entity/Employee.java, src/main/java/uos/uos25/employee/entity/EmployeeWorkingHistory.java, src/main/java/uos/uos25/inventory/entity/Inventory.java, src/main/java/uos/uos25/orders/entity/Orders.java, src/main/java/uos/uos25/product/entity/Product.java, src/main/java/uos/uos25/receipt/entity/Receipt.java
- 직원 인덱스 추가
- 직원업무기록 인덱스 추가
- 재고 인덱스 추가
- 주문 인덱스 추가
- 상품 인덱스 추가
- 영수증 인덱스 추가
=> feat: 인덱스 추가

src/main/java/uos/uos25/employee/entity/Employee.java, src/main/java/uos/uos25/receipt/dto/response/ReceiptGetResponseDTO.java
- 직원 주민등록번호 13->14로 변경
- 영수증 조회 시 결제 날짜 동봉
=> fix: 주민등록번호 자릿수 변경

src/main/java/uos/uos25/shop/dto/response/DisbursementGetResponseDTO.java
=> fix: 자금출납 날짜 추가

src/main/java/uos/uos25/common/DataInitializer.java, src/main/java/uos/uos25/employee/controller/EmployeeController.java, src/main/java/uos/uos25/employee/entity/Employee.java, src/main/java/uos/uos25/headQuarter/controller/HeadquarterController.java, src/main/java/uos/uos25/headQuarter/dto/response/HeadquarterGetResponseDTO.java, src/main/java/uos/uos25/headQuarter/service/HeadquarterService.java
- 본사 직원 조회 기능 구현
- 본사 더미 데이터 제거
- 직원 nullable 변경(잘못 생각함, 문서도 고쳐야 함.)
=> fix: 본사 직원 조회 기능 수정

build.gradle, src/main/java/uos/uos25/common/DataInitializer.java, src/main/resources/application.yml
- 오라클로 변경
- 영수증, 영수증상세 초기 데이터에서 제거(버그 땜시)
=> feat: 오라클 DB로 변경

src/main/java/uos/uos25/common/DataInitializer.java, src/main/java/uos/uos25/user/entity/Customer.java, src/main/resources/application.yml, src/test/java/uos/uos25/user/service/CustomerServiceTest.java
- 유저 생성 테스트 코드 작성
- 유저 전화번호 중복 테스트 코드 작성
- 유저 조회 테스트 코드 작성
- 유저 리스트 조회 테스트 코드 작성
- 유저 삭제 테스트 코드 작성
=> test: 고객 테스트 코드 작성

src/main/java/uos/uos25/user/dto/request/EmployeeCreateReqeustDTO.java, src/main/java/uos/uos25/user/dto/request/EmployeeUpdateReqeustDTO.java, src/main/java/uos/uos25/user/service/EmployeeService.java, src/main/resources/application.yml, src/test/java/uos/uos25/user/service/EmployeeServiceTest.java
- 직원 조회 테스트
- 직원 생성 테스트
- 직원 지점으로 조회 테스트
- 직원 수정 테스트
- 직원 수정 시 존재하지 않을 경우 예외 테스트
- 직원 퇴사 테스트
- update, retire return 값 추가
=> test: 직원 테스트 코드 작성
